#title: IV.3.1.1.1 - A prize/prizes will be awarded (yes)
#description: “IV.3.1.1.1 - A prize/prizes will be awarded (yes)” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F12_2014/PROCEDURE/PRIZE_AWARDED. The expected ontology instances are epo: epo:Procedure / epo:Lot / epo:DesignContestRegimeTerm / epo:Prize  .
#xpath: /TED_EXPORT/FORM_SECTION/F12_2014/PROCEDURE/PRIZE_AWARDED

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasProcurementScopeDividedIntoLot / epo:isSubjectToLotSpecificTerm / epo:definesPrize ?value . }