#title: IV.2.3 - Date of dispatch of invitations to participate to selected candidates (Date)
#description: “IV.2.3 - Date of dispatch of invitations to participate to selected candidates (Date)” in SF corresponds to “no match nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F12_2014/PROCEDURE/DATE_DISPATCH_INVITATIONS. The expected ontology instances are epo: epo:Procedure / epo:ProcessPlanningTerm / xsd:date .
#xpath: /TED_EXPORT/FORM_SECTION/F12_2014/PROCEDURE/DATE_DISPATCH_INVITATIONS

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:isSubjectToTerm  / epo:hasEstimatedTenderInvitationDate?value . }