#title: IV.3.4.1.1 - The decision of the jury is binding on the contracting authority/entity (yes)
#description: “IV.3.4.1.1 - The decision of the jury is binding on the contracting authority/entity (yes)” in SF corresponds to “BT-42 Jury Decision Binding” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F12_2014/PROCEDURE/DECISION_BINDING_CONTRACTING. The expected ontology instances are epo: epo:Procedure / epo:Lot / epo:DesignContestRegimeTerm / xsd:boolean .
#xpath: /TED_EXPORT/FORM_SECTION/F12_2014/PROCEDURE/DECISION_BINDING_CONTRACTING

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasProcurementScopeDividedIntoLot / epo:isSubjectToLotSpecificTerm / epo:hasJuryDecisionBinding true . }