#title: IV.2.7.3 - Information about authorised persons and opening procedure
#description: “IV.2.7.3 - Information about authorised persons and opening procedure” in SF corresponds to “BT-134 Public Opening Description” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F02_2014/PROCEDURE/OPENING_CONDITION/INFO_ADD. The expected ontology instances are epo: epo:Procedure / epo:Lot / epo:OpeningTerm / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F02_2014/PROCEDURE/OPENING_CONDITION/INFO_ADD

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasProcurementScopeDividedIntoLot / epo:isSubjectToLotSpecificTerm / epo:hasOpeningDescription ?value . }