#title: IV.2.6.1 - Tender must be valid until
#description: “IV.2.6.1 - Tender must be valid until” in SF corresponds to “BT-131 Deadline Receipt Tenders” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F02_2014/PROCEDURE/DATE_TENDER_VALID. The expected ontology instances are epo: epo:Procedure / epo:SubmissionTerm  / epo:Period / xsd:date .
#xpath: /TED_EXPORT/FORM_SECTION/F02_2014/PROCEDURE/DATE_TENDER_VALID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:isSubjectToProcedureSpecificTerm  / epo:hasValidityPeriod / epo:hasEnd ?value . }