#title: ND-ProcedureTenderingProcess
#description: “” The corresponding XML element is /*/cac:TenderingProcess. The expected ontology instances are epo: None .
#xpath: /*/cac:TenderingProcess



ASK WHERE { 
	None 
}