#title: ND-LocalLegalBasisWithID
#description: “” The corresponding XML element is /*/cac:TenderingTerms/cac:ProcurementLegislationDocumentReference[not(cbc:ID/text()=('CrossBorderLaw','LocalLegalBasis'))]. The expected ontology instances are epo: None .
#xpath: /*/cac:TenderingTerms/cac:ProcurementLegislationDocumentReference[not(cbc:ID/text()=('CrossBorderLaw','LocalLegalBasis'))]



ASK WHERE { 
	None 
}