#title: ND-ServiceProvider
#description: “” The corresponding XML element is /*/cac:ContractingParty/cac:Party. The expected ontology instances are epo: None .
#xpath: /*/cac:ContractingParty/cac:Party



ASK WHERE { 
	None 
}