#title: ND-GroupCompositionLotReference
#description: “” The corresponding XML element is /*/cac:TenderingTerms/cac:LotDistribution/cac:LotsGroup/cac:ProcurementProjectLotReference. The expected ontology instances are epo: None .
#xpath: /*/cac:TenderingTerms/cac:LotDistribution/cac:LotsGroup/cac:ProcurementProjectLotReference



ASK WHERE { 
	None 
}