#title: III.1.2.2 - List and brief description of selection criteria, indication of information and documentation required:
#description: “III.1.2.2 - List and brief description of selection criteria, indication of information and documentation required:” in SF corresponds to “BT-750 Selection Criteria Description” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F01_2014/LEFTI/ECONOMIC_FINANCIAL_INFO. The expected ontology instances are epo: epo:Lot / epo:SelectionCriterion / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F01_2014/LEFTI/ECONOMIC_FINANCIAL_INFO

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:specifiesSelectionCriterion / cccev:description ?value . }